# Generated by Django 4.1 on 2022-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userfeatures", "0002_projecttags_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "name",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("value", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="votes",
            name="unique_votes",
        ),
        migrations.AddField(
            model_name="feature",
            name="anon_downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feature",
            name="anon_upvotes",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="feature",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
    ]
